version: "3"
services:
  springboot-app:
    image: springboot-app
    build: .
    command: java -jar target/foodboardJar.jar
    depends_on:
      - mysqldb
    ports: 
      - 8081:8081
    environment:
      - SQL_DATABASE=foodboard
      - SQL_USER=admin
      - SQL_PASSWORD=admin
      - SQL_HOST=fb_database
      - SQL_PORT=5432

  fb_database:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data_foodboard:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=foodboard
volumes:
  postgres_data_foodboard: