version: "3"
services:
  springboot-app:
    image: springboot-app
    build: .
    command: java -jar target/foodboardJar.jar
    depends_on:
      - mysqldb
    ports: 
      - 8000-8999:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306

  hotel_db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=foodboard
volumes:
  postgres_data: